### ISSUE TITLE
Recipe Dataset Split

### ISSUE THREAD

**Issue by Mayer123** [ytyz1307zzh/KOALA#4]
Hi, I'm wondering if you can share your splits of the recipe dataset? Thanks!

**Comment by ytyz1307zzh** [comment]
Sure I have uploaded it to Google Drive (https://drive.google.com/drive/folders/1w6yuxeDtXXluH9bnNFFuHpRN6ci4Haz4?usp=sharing).

**Comment by Mayer123** [comment]
Thanks for sharing the data! I'm wondering if you could also provide training commands and evaluation scripts for this task as well? Much appreciated!

**Comment by ytyz1307zzh** [comment]
Sure. Just leave me your email address and I will zip the files and send it via email.

**Comment by iamjanvijay** [comment]
Hi @ytyz1307zzh @Mayer123! Thanks for sharing the pre-processed dataset. Can you please share the training commands and evaluation script with me? In case if my email id is required it is: iamjanvijay@gatech.edu
